### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by rafaelcorsi** [bloombar/git-developer-contribution-analysis#4]
```
(venv) ➜  aps1 gitlogstats -u bloombar -r https://github.com/bloombar/git-developer-contribution-analysis.git
Traceback (most recent call last):
  File "/home/rafaelc/.local/bin/gitlogstats", line 8, in <module>
    sys.exit(main())
  File "/home/rafaelc/.local/lib/python3.10/site-packages/gitlogstats/__main__.py", line 66, in main
    results = git_logs_parser.parse()
  File "/home/rafaelc/.local/lib/python3.10/site-packages/gitlogstats/GitLogsParser.py", line 97, in parse
    if(self.clean and (entry['merges'] == 0 and entry['commits'] == 0 and entry['insertions'] == 0 and entry['deletions'] == 0 and entry['files'] == 0)):
KeyError: 'merges'
```

from: Python 3.10.9 - linux

**Comment by bloombar** [comment]
@rafaelcorsi - I think this has already been resolved... but please install again with `pip`, try again, and let me know.

**Comment by Alex059** [comment]
Hello, problem is here https://github.com/bloombar/gitlogstats/blob/d16840209ac3f211fefa397018240e3f68fcfaa8/src/gitlogstats/GitLogsParser.py#L83

Need to uncomment.

**Comment by bloombar** [comment]
@Alex059 - thanks for pointing this out... I somehow didn't see it.  Fixed now.  I removed merges entirely from the stats because git doesn't seem to reliably report them in the git logs.  I'm still looking for a reliable way to count them.
